apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: darkx-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: darkx.example.bk
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
